#!/usr/bin/env bash
# stackwiz consumer bootstrap launcher.
#
# ============================================================================
# DO NOT EDIT THIS FILE.
#
# It is framework-managed: the canonical source lives in the stackwiz
# installer repo (src/stackwiz/share/bootstrap/bootstrap.sh) and is
# vendored into each consumer via:
#
#     docker run --rm -v "$PWD:/out" ghcr.io/chistokhinsv/stackwiz:latest \
#         extract-bootstrap --output /out --force
#
# Any edits made here will be lost on the next refresh. Per-project
# customization (SW_* arrays) lives in bootstrap.conf.sh alongside this
# file — THAT is what you edit.
# ============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

# Source per-project config if present. File is consumer-owned; it may be
# absent (the library has sensible defaults for every SW_* knob).
if [ -f "$HERE/bootstrap.conf.sh" ]; then
    # shellcheck source=/dev/null
    . "$HERE/bootstrap.conf.sh"
fi

# shellcheck source=/dev/null
. "$HERE/stackwiz-bootstrap.sh"
sw_bootstrap_main "$@"
