#!/usr/bin/env bash
# stackwiz-bootstrap.sh — shared bootstrap library for stackwiz consumers.
#
# ============================================================================
# DO NOT EDIT THIS FILE IN A CONSUMER REPO.
#
# It is framework-managed: the canonical source lives in the stackwiz
# installer repo (src/stackwiz/share/bootstrap/stackwiz-bootstrap.sh) and
# is vendored into each consumer via:
#
#     docker run --rm -v "$PWD:/out" ghcr.io/chistokhinsv/stackwiz:latest \
#         extract-bootstrap --output /out --force
#
# Any edits made here will be lost on the next refresh. Put per-project
# customization in bootstrap.sh (the stub that sources this library).
# Bug fixes and features belong upstream in the installer repo.
# ============================================================================
#
# Consumer stub contract:
#
#   #!/usr/bin/env bash
#   set -euo pipefail
#   SW_REQUIRED_PKGS=(curl ca-certificates jq openssl gettext-base python3)
#   SW_EXTRA_ENV=(CONSUL_HTTP_TOKEN STACKWIZ_HOST_MANIFEST_DIR)
#   SW_CHOWN_FILES=(.stackwiz.env .stackwiz.secrets.env .env)
#   SW_WRITABLE_DEFAULT=0                       # 1 = manifest mount RW by default
#   SW_WRITE_CMDS=(init-env)                    # args that force manifest RW
#   SW_READONLY_CMDS=(validate list info)       # args that force manifest RO
#   SW_HEADLESS_ARGS=(--auto --validate validate list info init-env)
#   . "$(dirname "$0")/stackwiz-bootstrap.sh"
#   sw_bootstrap_main "$@"
#
# All SW_* vars are optional and have sensible defaults (see below).

# ---------- defaults ----------
: "${STACKWIZ_IMAGE:=ghcr.io/chistokhinsv/stackwiz:latest}"
: "${STACKWIZ_STATE_DIR:=/var/lib/stackwiz}"
: "${SW_WRITABLE_DEFAULT:=0}"

if ! declare -p SW_REQUIRED_PKGS >/dev/null 2>&1; then
  SW_REQUIRED_PKGS=(curl ca-certificates jq openssl gettext-base python3)
fi
if ! declare -p SW_EXTRA_ENV >/dev/null 2>&1; then
  SW_EXTRA_ENV=()
fi
if ! declare -p SW_CHOWN_FILES >/dev/null 2>&1; then
  SW_CHOWN_FILES=(.stackwiz.env .stackwiz.secrets.env .env)
fi
if ! declare -p SW_WRITE_CMDS >/dev/null 2>&1; then
  SW_WRITE_CMDS=(init-env)
fi
if ! declare -p SW_READONLY_CMDS >/dev/null 2>&1; then
  SW_READONLY_CMDS=(validate list info)
fi
if ! declare -p SW_HEADLESS_ARGS >/dev/null 2>&1; then
  SW_HEADLESS_ARGS=(--auto --validate validate list info init-env)
fi

# Canonical env vars always passed through to the installer container.
# Consumer-specific extras go in SW_EXTRA_ENV.
_SW_BASE_ENV=(
  CONSUL_HTTP_ADDR
  VAULT_ADDR
  VAULT_TOKEN
  # TLS-verify policy for Vault traffic. STACKWIZ_VAULT_VERIFY=false opts
  # out (needed when Vault uses a self-signed cert that isn't in the
  # container's trust bundle); VAULT_CACERT points at a custom CA file.
  # Both must reach the installer container or the engine's probe / adopt
  # logic and every install script sourcing stackwiz-bootstrap.sh's
  # sw_vault_curl_tls would otherwise default to strict verify.
  STACKWIZ_VAULT_VERIFY
  VAULT_CACERT
  CF_DNS_API_TOKEN
  AWS_DNS_ACCESS_KEY_ID
  AWS_DNS_SECRET_ACCESS_KEY
  CERTBOT_EMAIL
  STACKWIZ_TLS_FORCE
)

sw_log() { echo "[bootstrap] $*"; }
sw_warn() { echo "warn: $*" >&2; }
sw_err() { echo "error: $*" >&2; }

# Emit curl TLS options for Vault. See stackwiz.vault_client.resolve_verify
# for precedence:
#   VAULT_CACERT=/path         → --cacert /path
#   STACKWIZ_VAULT_VERIFY=false → -k  (explicit opt-out; logged as warning)
#   otherwise                  → default (system CA trust, verify on)
sw_vault_curl_tls() {
  if [ -n "${VAULT_CACERT:-}" ]; then
    printf -- '--cacert %s' "${VAULT_CACERT}"
  elif [ "${STACKWIZ_VAULT_VERIFY:-true}" = "false" ] \
    || [ "${STACKWIZ_VAULT_VERIFY:-true}" = "0" ] \
    || [ "${STACKWIZ_VAULT_VERIFY:-true}" = "no" ]; then
    printf -- '-k'
  fi
}

# Vault preflight for per-component installers.
#
# Use from install/*.sh like:
#
#   . "${STATE_DIR}/bin/stackwiz-bootstrap.sh"
#   sw_require_vault  # hard-errors with an actionable message if Vault
#                     # is unreachable or the token lacks auth
#
# Why: without this, an installer that reads secrets via the vault
# client silently gets empty strings and bakes them into containers —
# install "succeeds" but runtime is broken. Surfacing the failure at
# install time is ~100x cheaper to debug.
sw_require_vault() {
  local who="${1:-installer}"
  if [ -z "${VAULT_ADDR:-}" ]; then
    sw_err "${who}: VAULT_ADDR not set — Vault discovery failed"
    sw_err "       check 'bootstrap.sh info' output for 'discovered Vault at ...' line;"
    sw_err "       if missing, export CONSUL_HTTP_TOKEN or persist one at"
    sw_err "       ${STACKWIZ_STATE_DIR}/consul-http-token and re-run."
    exit 1
  fi
  if [ -z "${VAULT_TOKEN:-}" ]; then
    sw_err "${who}: VAULT_TOKEN not set — cannot authenticate to Vault at ${VAULT_ADDR}"
    exit 1
  fi
  local code
  # shellcheck disable=SC2046  # intentional word-split of TLS opts
  code=$(curl -s $(sw_vault_curl_tls) -o /dev/null -w '%{http_code}' \
    -H "X-Vault-Token: ${VAULT_TOKEN}" \
    "${VAULT_ADDR%/}/v1/auth/token/lookup-self" 2>/dev/null || echo 000)
  case "$code" in
    200) : ;;  # authenticated, good
    403) sw_err "${who}: VAULT_TOKEN lacks permission to self-lookup at ${VAULT_ADDR}"; exit 1 ;;
    000) sw_err "${who}: Vault unreachable at ${VAULT_ADDR} (network / TLS)"; exit 1 ;;
    *)   sw_err "${who}: Vault auth check returned HTTP ${code} at ${VAULT_ADDR}"; exit 1 ;;
  esac
}

# Map required package binary name -> apt package name for edge cases.
_sw_pkg_for() {
  case "$1" in
    envsubst) echo "gettext-base" ;;
    *) echo "$1" ;;
  esac
}

sw_bootstrap_source_env() {
  local f="${1:-$PWD/.env}"
  if [ -f "$f" ]; then
    if [ -r "$f" ]; then
      set -a; . "$f"; set +a
    else
      sw_warn "$f exists but is not readable (run: sudo chown \$(id -u):\$(id -g) $f)"
    fi
  fi
}

sw_bootstrap_require_sudo() {
  if ! command -v sudo >/dev/null; then
    sw_err "sudo is required but not installed"
    echo "       run as root: apt-get install -y sudo" >&2
    exit 1
  fi
}

# Install declared prerequisites. Uses SW_REQUIRED_PKGS unless args given.
sw_bootstrap_ensure_pkgs() {
  local pkgs=("$@")
  [ "${#pkgs[@]}" -eq 0 ] && pkgs=("${SW_REQUIRED_PKGS[@]}")
  local needed=()
  local p bin apt_name
  for p in "${pkgs[@]}"; do
    # Treat multi-token entries (e.g. "curl ca-certificates") as apt-name-only
    # when the first token isn't on PATH. Probe the first token.
    bin="${p%% *}"
    # Virtual names that aren't invoked as commands (like ca-certificates).
    case "$bin" in
      ca-certificates|gettext-base)
        dpkg -s "$bin" >/dev/null 2>&1 || needed+=("$bin")
        continue
        ;;
    esac
    if ! command -v "$bin" >/dev/null; then
      apt_name="$(_sw_pkg_for "$bin")"
      needed+=("$apt_name")
      # Always pair curl with ca-certificates for TLS.
      [ "$bin" = "curl" ] && needed+=("ca-certificates")
    fi
  done
  if [ "${#needed[@]}" -gt 0 ]; then
    sw_log "installing host dependencies: ${needed[*]}"
    sudo apt-get update -qq && sudo apt-get install -y -qq "${needed[@]}"
  fi
}

# Auto-load CONSUL_HTTP_TOKEN from disk if it's not already exported.
# Consumers frequently persist the token to
# ${STACKWIZ_STATE_DIR}/<consumer>/consul-http-token (installers write
# it there), but SW_EXTRA_ENV=(CONSUL_HTTP_TOKEN) only forwards a value
# that is already in the environment. Without this helper, a perfectly
# good on-disk token is silently ignored and every downstream Consul
# ACL check fails as the anonymous identity — which then breaks Vault
# discovery, service discovery, and secret reads.
sw_bootstrap_load_consul_token() {
  [ -n "${CONSUL_HTTP_TOKEN:-}" ] && return 0
  local cand f
  cand=(
    "${STACKWIZ_STATE_DIR}/consul-http-token"
  )
  # Also try any per-consumer subdirectory: installers write to
  # ${STACKWIZ_STATE_DIR}/<name>/consul-http-token. Glob them all so
  # we don't hard-code consumer names.
  for f in "${STACKWIZ_STATE_DIR}"/*/consul-http-token; do
    [ -f "$f" ] && cand+=("$f")
  done
  cand+=("/etc/stackwiz/consul-http-token" "${HOME:-/root}/.consul/http-token")
  # Token files are typically chmod 0600 root:root so a regular-user
  # `[ -r ]` test returns false. Don't gate on readability — probe
  # with `sudo test -f` and read via sudo, falling back to plain cat
  # if the file happens to be user-owned.
  for f in "${cand[@]}"; do
    if sudo test -f "$f" 2>/dev/null || [ -f "$f" ]; then
      CONSUL_HTTP_TOKEN="$(sudo cat "$f" 2>/dev/null || cat "$f" 2>/dev/null || true)"
      CONSUL_HTTP_TOKEN="${CONSUL_HTTP_TOKEN%$'\n'}"  # strip trailing newline
      if [ -n "$CONSUL_HTTP_TOKEN" ]; then
        export CONSUL_HTTP_TOKEN
        sw_log "loaded CONSUL_HTTP_TOKEN from $f"
        return 0
      fi
    fi
  done
}

sw_bootstrap_discover_consul() {
  [ -n "${CONSUL_HTTP_ADDR:-}" ] && return 0
  local addr
  for addr in "http://127.0.0.1:8500" "http://consul.$(hostname -d 2>/dev/null || echo local):8500"; do
    if curl -sf "${addr}/v1/status/leader" >/dev/null 2>&1; then
      CONSUL_HTTP_ADDR="$addr"
      export CONSUL_HTTP_ADDR
      sw_log "discovered Consul at ${CONSUL_HTTP_ADDR}"

      # ACL preflight — if the effective token (anonymous or explicit)
      # can't even list `consul` (every agent registers itself), no
      # downstream service discovery will work and we'll cascade into
      # silent failures at Vault discovery, secret reads, and registrar
      # DNS lookups. Probe once, here, so the operator gets one clear
      # message instead of a dozen "not found" symptoms later.
      local hdr="" probe
      [ -n "${CONSUL_HTTP_TOKEN:-}" ] && hdr="X-Consul-Token: ${CONSUL_HTTP_TOKEN}"
      probe=$(curl -sf ${hdr:+-H "$hdr"} \
        "${CONSUL_HTTP_ADDR}/v1/catalog/service/consul" 2>/dev/null || echo "[]")
      if [ "$probe" = "[]" ] || [ -z "$probe" ]; then
        if [ -z "${CONSUL_HTTP_TOKEN:-}" ]; then
          sw_warn "Consul anonymous token lacks service:read — export CONSUL_HTTP_TOKEN or persist one at ${STACKWIZ_STATE_DIR}/consul-http-token; service discovery will be degraded"
        else
          sw_warn "Consul token lacks service:read on \"consul\" — check policy; service discovery will be degraded"
        fi
      fi
      return 0
    fi
  done
}

sw_bootstrap_discover_vault() {
  [ -n "${VAULT_ADDR:-}" ] && return 0
  if [ -z "${CONSUL_HTTP_ADDR:-}" ]; then
    sw_warn "vault discovery skipped: CONSUL_HTTP_ADDR not set (no Consul to query)"
    return 0
  fi

  local hdr="" resp
  [ -n "${CONSUL_HTTP_TOKEN:-}" ] && hdr="X-Consul-Token: ${CONSUL_HTTP_TOKEN}"
  resp=$(curl -sf ${hdr:+-H "$hdr"} \
    "${CONSUL_HTTP_ADDR}/v1/catalog/service/vault" 2>/dev/null || echo "__CURL_ERR__")

  if [ "$resp" = "__CURL_ERR__" ]; then
    sw_warn "vault discovery skipped: consul query failed (check CONSUL_HTTP_TOKEN / ACL)"
    return 0
  fi

  local svc
  svc=$(printf '%s' "$resp" | python3 -c "
import sys,json
try:
    r=json.load(sys.stdin)
except Exception:
    sys.exit(0)
if r:
    s=r[0]; addr=s.get('ServiceAddress') or s['Address']; port=s['ServicePort']
    print(f'https://{addr}:{port}')
" 2>/dev/null || true)

  if [ -n "$svc" ]; then
    VAULT_ADDR="$svc"
    export VAULT_ADDR
    sw_log "discovered Vault at ${VAULT_ADDR}"
  elif [ "$resp" = "[]" ]; then
    sw_warn "no Vault service registered in Consul (under tag or name 'vault') — secret reads will show (not in vault)"
  else
    sw_warn "vault discovery: unexpected Consul response; skipping"
  fi
}

# Remove distribution-provided Docker packages that conflict with docker-ce.
# Per https://docs.docker.com/engine/install/debian/ "Uninstall old versions":
# docker.io, docker-compose, docker-doc, podman-docker, containerd and runc
# ship colliding binaries + runtimes. Installing docker-ce on top of them
# leaves mixed state (duplicate containerd, wrong `docker` on PATH, unit
# file conflicts). Scan dpkg first so the output is quiet on fresh hosts.
#
# Called only on the fresh-install path — if `command -v docker` already
# succeeds (including distro-provided docker.io), sw_bootstrap_ensure_docker
# takes the fast-path skip and never reaches here.
sw_bootstrap_remove_conflicting_pkgs() {
  local pkgs=(docker.io docker-compose docker-doc podman-docker containerd runc)
  local to_remove=()
  local p
  for p in "${pkgs[@]}"; do
    dpkg -s "$p" >/dev/null 2>&1 && to_remove+=("$p")
  done
  if [ "${#to_remove[@]}" -gt 0 ]; then
    sw_log "removing conflicting Docker packages: ${to_remove[*]}"
    sudo apt-get remove -y -qq "${to_remove[@]}"
  fi
}

sw_bootstrap_ensure_docker() {
  if command -v docker >/dev/null; then
    sudo mkdir -p "${STACKWIZ_STATE_DIR}"
    return 0
  fi

  # Install via Docker's official signed apt repository. Avoids the
  # unverified `curl | sh` pattern: the GPG key is pinned on disk and
  # apt verifies every package signature against it.
  if ! command -v apt-get >/dev/null 2>&1 || [ ! -f /etc/os-release ]; then
    sw_err "Docker install requires apt-get (Debian/Ubuntu host)."
    sw_err "Install Docker for your distro and re-run bootstrap."
    exit 1
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  local distro="${ID:-}" codename="${VERSION_CODENAME:-}"
  case "$distro" in
    debian|ubuntu) ;;
    *)
      sw_err "unsupported distro '$distro' for auto Docker install."
      sw_err "Install Docker manually and re-run bootstrap."
      exit 1
      ;;
  esac
  if [ -z "$codename" ]; then
    sw_err "/etc/os-release missing VERSION_CODENAME; cannot pin apt suite."
    exit 1
  fi

  # Purge conflicting distribution packages BEFORE adding the Docker repo
  # so `apt install docker-ce ...` below doesn't hit the conflict Docker's
  # own install guide warns about.
  sw_bootstrap_remove_conflicting_pkgs

  sw_log "installing Docker from ${distro} apt repository (${codename})"

  local keyring="/etc/apt/keyrings/docker.asc"
  local listfile="/etc/apt/sources.list.d/docker.list"
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL "https://download.docker.com/linux/${distro}/gpg" \
    -o "${keyring}"
  sudo chmod a+r "${keyring}"

  local arch
  arch=$(dpkg --print-architecture)
  echo "deb [arch=${arch} signed-by=${keyring}] https://download.docker.com/linux/${distro} ${codename} stable" \
    | sudo tee "${listfile}" >/dev/null

  sudo apt-get update -qq
  sudo apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

  sudo mkdir -p "${STACKWIZ_STATE_DIR}"
}

# Pull image; fall back to cached copy if the registry is unreachable.
# Streams docker pull progress (layer download bars, status messages) to
# the operator's terminal — tee'd into a temp file so we can still parse
# the Status: line afterwards to distinguish "refreshed" from "up to date".
# On failure, the full error is already on stderr so the operator sees it.
sw_bootstrap_pull_image() {
  local image="${1:-$STACKWIZ_IMAGE}"
  local pull_log rc
  pull_log="$(mktemp)"
  # stdbuf -oL keeps docker's progress lines line-buffered so the tee shows
  # them live instead of batching until close; falls back to plain pipe if
  # stdbuf isn't installed (coreutils is standard, but just in case).
  if command -v stdbuf >/dev/null 2>&1; then
    set -o pipefail
    stdbuf -oL sudo docker pull "$image" 2>&1 | tee "$pull_log"
    rc=${PIPESTATUS[0]}
    set +o pipefail
  else
    set -o pipefail
    sudo docker pull "$image" 2>&1 | tee "$pull_log"
    rc=${PIPESTATUS[0]}
    set +o pipefail
  fi

  if [ "$rc" -eq 0 ]; then
    local status digest created
    status=$(grep -E '^Status:' "$pull_log" | tail -n1)
    digest=$(sudo docker image inspect --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$image" 2>/dev/null || true)
    created=$(sudo docker image inspect --format '{{.Created}}' "$image" 2>/dev/null || true)
    if echo "$status" | grep -q 'Downloaded newer image'; then
      sw_log "image refreshed (${digest:-$image}, built ${created})"
    else
      sw_log "image up to date (${digest:-$image}, built ${created})"
    fi
    rm -f "$pull_log"
    return 0
  fi

  rm -f "$pull_log"
  if sudo docker image inspect "$image" >/dev/null 2>&1; then
    local digest created
    digest=$(sudo docker image inspect --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$image" 2>/dev/null || true)
    created=$(sudo docker image inspect --format '{{.Created}}' "$image" 2>/dev/null || true)
    sw_warn "docker pull failed (see output above); using cached image"
    if [ -n "$digest" ]; then
      sw_warn "cached image: ${digest} (built ${created})"
    else
      sw_warn "cached image: ${image} (built ${created}; no RepoDigests — likely a local build)"
    fi
  else
    sw_err "docker pull failed (see output above); image $image not found locally either"
    exit 1
  fi
}

# Parse positional args to set SW_HEADLESS and SW_WRITABLE_MANIFEST.
# Writable resolution:
#   - start from SW_WRITABLE_DEFAULT
#   - SW_WRITE_CMDS match -> force 1
#   - SW_READONLY_CMDS match -> force 0 (takes precedence over write match)
sw_bootstrap_parse_args() {
  SW_HEADLESS=0
  SW_WRITABLE_MANIFEST="${SW_WRITABLE_DEFAULT}"
  local arg cmd
  for arg in "$@"; do
    for cmd in "${SW_HEADLESS_ARGS[@]}"; do
      [ "$arg" = "$cmd" ] && SW_HEADLESS=1
    done
    for cmd in "${SW_WRITE_CMDS[@]}"; do
      [ "$arg" = "$cmd" ] && SW_WRITABLE_MANIFEST=1
    done
    for cmd in "${SW_READONLY_CMDS[@]}"; do
      [ "$arg" = "$cmd" ] && SW_WRITABLE_MANIFEST=0
    done
  done
  export SW_HEADLESS SW_WRITABLE_MANIFEST
}

# Run the installer container. Any args after the function name are passed
# through to wizinstall as the entrypoint command line.
sw_bootstrap_run() {
  local docker_flags=(--rm)
  [ "${SW_HEADLESS}" -eq 0 ] && docker_flags+=(-it)

  local manifest_mount
  if [ "${SW_WRITABLE_MANIFEST}" -eq 1 ]; then
    manifest_mount="$PWD:/manifest"
  else
    manifest_mount="$PWD:/manifest:ro"
  fi

  local env_args=()
  local v
  for v in "${_SW_BASE_ENV[@]}" "${SW_EXTRA_ENV[@]}"; do
    env_args+=(-e "${v}=${!v:-}")
  done
  # Always propagate host state/manifest paths so install scripts can reason
  # about the real filesystem locations.
  env_args+=(-e "STACKWIZ_HOST_STATE_DIR=${STACKWIZ_STATE_DIR}")
  env_args+=(-e "STACKWIZ_HOST_MANIFEST_DIR=$PWD")

  sudo docker run "${docker_flags[@]}" \
    --privileged --pid=host --network=host \
    -v "${manifest_mount}" \
    -v "${STACKWIZ_STATE_DIR}:/state" \
    "${env_args[@]}" \
    "${STACKWIZ_IMAGE}" "$@"
}

# Reclaim ownership of any files the container wrote as root.
sw_bootstrap_chown_outputs() {
  [ "${SW_WRITABLE_MANIFEST}" -eq 1 ] || return 0
  local f
  for f in "${SW_CHOWN_FILES[@]}"; do
    if [ -f "$PWD/$f" ]; then
      sudo chown "$(id -u):$(id -g)" "$PWD/$f" 2>/dev/null || true
    fi
  done
}

# Full bootstrap lifecycle. Consumer stubs call `sw_bootstrap_main "$@"`.
sw_bootstrap_main() {
  sw_bootstrap_source_env
  sw_bootstrap_require_sudo
  sw_bootstrap_ensure_pkgs
  # Load on-disk token BEFORE Consul discovery so the ACL preflight in
  # discover_consul can use it.
  sw_bootstrap_load_consul_token
  sw_bootstrap_discover_consul
  sw_bootstrap_discover_vault
  sw_bootstrap_ensure_docker
  sw_bootstrap_pull_image
  sw_bootstrap_parse_args "$@"

  local rc=0
  sw_bootstrap_run "$@" || rc=$?
  sw_bootstrap_chown_outputs
  exit "$rc"
}
